#!/bin/bash
set -eu -o pipefail

ROLE_NAME=$1

OUTPUT_FILE=/opt/vault/bin/setup-vault.sh
AWS_ACCOUNT_ID=$(curl http://169.254.169.254/latest/meta-data/iam/info | jq .InstanceProfileArn | cut -d: -f5)

# Write the setup-vault script
cat << EOF > $OUTPUT_FILE
#!/bin/bash
set -eu -o pipefail

# Takes the root token as an argument
# Sets up the vault permissions and deletes the root token when it's done
ROOT_TOKEN=\$1

# Authorize with the root token
vault auth \$ROOT_TOKEN

# Enable the aws auth backend
vault auth-enable aws

# Enable audit logging
AUDIT_LOG=/opt/vault/log/audit.log
vault audit-enable file file_path=\$AUDIT_LOG

# Mount the quorum path
vault mount -path=nodes -default-lease-ttl=30 -description="Private data related to quorum node" kv

# Create policies
EXIMCHAIN_NODE_POLICY=/opt/vault/config/policies/eximchain-node.hcl
vault policy-write tx_executor \$EXIMCHAIN_NODE_POLICY

# Write policy to the roles used by instances
vault write auth/aws/role/$ROLE_NAME auth_type=iam policies=tx_executor bound_iam_principal_arn=arn:aws:iam::$AWS_ACCOUNT_ID:role/$ROLE_NAME

# Revoke the root token to reduce security risk
vault token-revoke \$ROOT_TOKEN
EOF

# Give permission to run the script
sudo chown ubuntu $OUTPUT_FILE
sudo chmod 744 $OUTPUT_FILE
